In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [6]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [7]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [8]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [9]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [11]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

#### ANN Regression Problem statement

In [12]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [13]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

2026-03-11 13:10:45.980270: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-03-11 13:10:45.980321: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-03-11 13:10:45.980334: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.92 GB
2026-03-11 13:10:45.980381: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-03-11 13:10:45.980407: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [14]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [15]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [16]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100

2026-03-11 13:10:56.549360: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.

250/250 [==============================] - 2s 4ms/step - loss: 100425.5312 - mae: 100425.5312 - val_loss: 98704.2500 - val_mae: 98704.2500
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 100359.6406 - mae: 100359.6406 - val_loss: 98586.4219 - val_mae: 98586.4219
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 100197.4688 - mae: 100197.4688 - val_loss: 98379.3359 - val_mae: 98379.3359
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 99953.2812 - mae: 99953.2812 - val_loss: 98093.2109 - val_mae: 98093.2109
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 99624.6797 - mae: 99624.6797 - val_loss: 97744.8047 - val_mae: 97744.8047
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 99269.4453 - mae: 99269.4453 - val_loss: 97392.0312 - val_mae: 97392.0312
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 98895.2578 - mae: 98895.2578 - val_loss: 97034.9609 - val_mae: 97034.9609
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 98508.3984 - mae: 98508.3984 - val_loss: 96718.4844 - val_mae: 96718.4844
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 98160.7578 - mae: 98160.7578 - val_loss: 96416.7812 - val_mae: 96416.7812
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 97812.3281 - mae: 97812.3281 - val_loss: 96087.4453 - val_mae: 96087.4453
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 97454.3516 - mae: 97454.3516 - val_loss: 95710.1719 - val_mae: 95710.1719
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 97046.2812 - mae: 97046.2812 - val_loss: 95285.9688 - val_mae: 95285.9688
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 96615.9062 - mae: 96615.9062 - val_loss: 94826.9766 - val_mae: 94826.9766
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 96171.1953 - mae: 96171.1953 - val_loss: 94352.5469 - val_mae: 94352.5469
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 95695.5859 - mae: 95695.5859 - val_loss: 93840.5391 - val_mae: 93840.5391
Epoch 16/100
250/250 [==============================] - 1s 3ms/step - loss: 95197.5469 - mae: 95197.5469 - val_loss: 93307.9375 - val_mae: 93307.9375
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 94693.4453 - mae: 94693.4453 - val_loss: 92805.5469 - val_mae: 92805.5469
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 94182.0391 - mae: 94182.0391 - val_loss: 92278.1719 - val_mae: 92278.1719
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 93679.3828 - mae: 93679.3828 - val_loss: 91752.8203 - val_mae: 91752.8203
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 93173.5703 - mae: 93173.5703 - val_loss: 91234.6016 - val_mae: 91234.6016
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 92650.0469 - mae: 92650.0469 - val_loss: 90749.3672 - val_mae: 90749.3672
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 92136.9453 - mae: 92136.9453 - val_loss: 90194.1172 - val_mae: 90194.1172
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 91605.7109 - mae: 91605.7109 - val_loss: 89667.7812 - val_mae: 89667.7812
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 91080.2891 - mae: 91080.2891 - val_loss: 89131.9922 - val_mae: 89131.9922
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 90528.3672 - mae: 90528.3672 - val_loss: 88599.9844 - val_mae: 88599.9844
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 89992.9375 - mae: 89992.9375 - val_loss: 88026.0781 - val_mae: 88026.0781
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 89442.3906 - mae: 89442.3906 - val_loss: 87499.1797 - val_mae: 87499.1797
Epoch 28/100
250/250 [==============================] - 1s 3ms/step - loss: 88878.2031 - mae: 88878.2031 - val_loss: 86906.0625 - val_mae: 86906.0625
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 88263.1875 - mae: 88263.1875 - val_loss: 86304.4219 - val_mae: 86304.4219
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 87688.1406 - mae: 87688.1406 - val_loss: 85715.6719 - val_mae: 85715.6719
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 87102.3047 - mae: 87102.3047 - val_loss: 85133.8672 - val_mae: 85133.8672
Epoch 32/100
250/250 [==============================] - 1s 3ms/step - loss: 86508.6484 - mae: 86508.6484 - val_loss: 84652.2656 - val_mae: 84652.2656
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 85927.0781 - mae: 85927.0781 - val_loss: 83966.2812 - val_mae: 83966.2812
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 85349.4062 - mae: 85349.4062 - val_loss: 83424.2891 - val_mae: 83424.2891
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 84732.3438 - mae: 84732.3438 - val_loss: 82821.4219 - val_mae: 82821.4219
Epoch 36/100
250/250 [==============================] - 1s 3ms/step - loss: 84124.3750 - mae: 84124.3750 - val_loss: 82174.0781 - val_mae: 82174.0781
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 83512.5078 - mae: 83512.5078 - val_loss: 81587.4141 - val_mae: 81587.4141
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 82902.8828 - mae: 82902.8828 - val_loss: 80944.3281 - val_mae: 80944.3281
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 82286.6172 - mae: 82286.6172 - val_loss: 80334.7188 - val_mae: 80334.7188
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 81686.7031 - mae: 81686.7031 - val_loss: 79757.8438 - val_mae: 79757.8438
Epoch 41/100
250/250 [==============================] - 1s 4ms/step - loss: 81057.5781 - mae: 81057.5781 - val_loss: 79219.6250 - val_mae: 79219.6250
Epoch 42/100
250/250 [==============================] - 1s 4ms/step - loss: 80433.1484 - mae: 80433.1484 - val_loss: 78501.0703 - val_mae: 78501.0703
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 79802.5781 - mae: 79802.5781 - val_loss: 77875.5625 - val_mae: 77875.5625
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 79169.6016 - mae: 79169.6016 - val_loss: 77208.5312 - val_mae: 77208.5312
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 78518.8203 - mae: 78518.8203 - val_loss: 76600.8594 - val_mae: 76600.8594
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 77861.8750 - mae: 77861.8750 - val_loss: 75952.9375 - val_mae: 75952.9375
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 77221.6875 - mae: 77221.6875 - val_loss: 75246.9297 - val_mae: 75246.9297
Epoch 48/100
250/250 [==============================] - 1s 3ms/step - loss: 76571.2031 - mae: 76571.2031 - val_loss: 74608.1250 - val_mae: 74608.1250
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 75900.8203 - mae: 75900.8203 - val_loss: 74040.5234 - val_mae: 74040.5234
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 75241.4688 - mae: 75241.4688 - val_loss: 73302.4062 - val_mae: 73302.4062
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 74592.6484 - mae: 74592.6484 - val_loss: 72670.5312 - val_mae: 72670.5312
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 73944.0156 - mae: 73944.0156 - val_loss: 72023.8984 - val_mae: 72023.8984
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 73250.6484 - mae: 73250.6484 - val_loss: 71634.7734 - val_mae: 71634.7734
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 72670.0781 - mae: 72670.0781 - val_loss: 70708.3672 - val_mae: 70708.3672
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 71926.8906 - mae: 71926.8906 - val_loss: 70191.7109 - val_mae: 70191.7109
Epoch 56/100
250/250 [==============================] - 1s 4ms/step - loss: 71259.7812 - mae: 71259.7812 - val_loss: 69371.8594 - val_mae: 69371.8594
Epoch 57/100
250/250 [==============================] - 1s 3ms/step - loss: 70592.5781 - mae: 70592.5781 - val_loss: 68755.7188 - val_mae: 68755.7188
Epoch 58/100
250/250 [==============================] - 1s 4ms/step - loss: 69940.4141 - mae: 69940.4141 - val_loss: 68179.9453 - val_mae: 68179.9453
Epoch 59/100
250/250 [==============================] - 1s 3ms/step - loss: 69285.3906 - mae: 69285.3906 - val_loss: 67536.8203 - val_mae: 67536.8203
Epoch 60/100
250/250 [==============================] - 1s 3ms/step - loss: 68638.0547 - mae: 68638.0547 - val_loss: 66836.6719 - val_mae: 66836.6719
Epoch 61/100
250/250 [==============================] - 1s 3ms/step - loss: 67974.9219 - mae: 67974.9219 - val_loss: 66294.1406 - val_mae: 66294.1406
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 67332.4375 - mae: 67332.4375 - val_loss: 65779.1094 - val_mae: 65779.1094
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 66715.1719 - mae: 66715.1719 - val_loss: 64980.7148 - val_mae: 64980.7148
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 66091.9922 - mae: 66091.9922 - val_loss: 64354.6484 - val_mae: 64354.6484
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 65460.8906 - mae: 65460.8906 - val_loss: 63767.8438 - val_mae: 63767.8438
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 64852.2695 - mae: 64852.2695 - val_loss: 63626.6445 - val_mae: 63626.6445
Epoch 67/100
250/250 [==============================] - 1s 3ms/step - loss: 64185.2695 - mae: 64185.2695 - val_loss: 62618.0312 - val_mae: 62618.0312
Epoch 68/100
250/250 [==============================] - 1s 3ms/step - loss: 63611.6953 - mae: 63611.6953 - val_loss: 61931.4297 - val_mae: 61931.4297
Epoch 69/100
250/250 [==============================] - 1s 3ms/step - loss: 63024.4570 - mae: 63024.4570 - val_loss: 61329.4648 - val_mae: 61329.4648
Epoch 70/100
250/250 [==============================] - 1s 3ms/step - loss: 62377.0234 - mae: 62377.0234 - val_loss: 60741.8867 - val_mae: 60741.8867
Epoch 71/100
250/250 [==============================] - 1s 4ms/step - loss: 61808.7227 - mae: 61808.7227 - val_loss: 60287.7070 - val_mae: 60287.7070
Epoch 72/100
250/250 [==============================] - 1s 4ms/step - loss: 61233.7227 - mae: 61233.7227 - val_loss: 59633.2148 - val_mae: 59633.2148
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 60648.9258 - mae: 60648.9258 - val_loss: 59122.2461 - val_mae: 59122.2461
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 60039.9492 - mae: 60039.9492 - val_loss: 58650.3906 - val_mae: 58650.3906
Epoch 75/100
250/250 [==============================] - 1s 4ms/step - loss: 59479.2266 - mae: 59479.2266 - val_loss: 58160.8945 - val_mae: 58160.8945
Epoch 76/100
250/250 [==============================] - 1s 4ms/step - loss: 58948.3242 - mae: 58948.3242 - val_loss: 57542.4570 - val_mae: 57542.4570
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 58387.3945 - mae: 58387.3945 - val_loss: 57067.0117 - val_mae: 57067.0117
Epoch 78/100
250/250 [==============================] - 1s 3ms/step - loss: 57867.4844 - mae: 57867.4844 - val_loss: 56897.5547 - val_mae: 56897.5547
Epoch 79/100
250/250 [==============================] - 1s 3ms/step - loss: 57393.4219 - mae: 57393.4219 - val_loss: 56054.2148 - val_mae: 56054.2148
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 56831.6055 - mae: 56831.6055 - val_loss: 55588.7695 - val_mae: 55588.7695
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 56347.9570 - mae: 56347.9570 - val_loss: 55194.6055 - val_mae: 55194.6055
Epoch 82/100
250/250 [==============================] - 1s 3ms/step - loss: 55822.1406 - mae: 55822.1406 - val_loss: 54730.5898 - val_mae: 54730.5898
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 55422.4375 - mae: 55422.4375 - val_loss: 54315.2070 - val_mae: 54315.2070
Epoch 84/100
250/250 [==============================] - 1s 3ms/step - loss: 54950.2930 - mae: 54950.2930 - val_loss: 53940.1250 - val_mae: 53940.1250
Epoch 85/100
250/250 [==============================] - 1s 3ms/step - loss: 54515.8750 - mae: 54515.8750 - val_loss: 53594.8047 - val_mae: 53594.8047
Epoch 86/100
250/250 [==============================] - 1s 3ms/step - loss: 54118.3359 - mae: 54118.3359 - val_loss: 53150.0156 - val_mae: 53150.0156
Epoch 87/100
250/250 [==============================] - 1s 3ms/step - loss: 53711.1484 - mae: 53711.1484 - val_loss: 52801.5938 - val_mae: 52801.5938
Epoch 88/100
250/250 [==============================] - 1s 3ms/step - loss: 53351.9727 - mae: 53351.9727 - val_loss: 52588.9062 - val_mae: 52588.9062
Epoch 89/100
250/250 [==============================] - 1s 3ms/step - loss: 52976.4023 - mae: 52976.4023 - val_loss: 52225.8672 - val_mae: 52225.8672
Epoch 90/100
250/250 [==============================] - 1s 3ms/step - loss: 52665.5195 - mae: 52665.5195 - val_loss: 51905.6016 - val_mae: 51905.6016
Epoch 91/100
250/250 [==============================] - 1s 3ms/step - loss: 52323.1914 - mae: 52323.1914 - val_loss: 51875.7656 - val_mae: 51875.7656
Epoch 92/100
250/250 [==============================] - 1s 3ms/step - loss: 52074.5742 - mae: 52074.5742 - val_loss: 51406.3750 - val_mae: 51406.3750
Epoch 93/100
250/250 [==============================] - 1s 3ms/step - loss: 51747.8672 - mae: 51747.8672 - val_loss: 51397.8125 - val_mae: 51397.8125
Epoch 94/100
250/250 [==============================] - 1s 3ms/step - loss: 51524.5273 - mae: 51524.5273 - val_loss: 51033.7070 - val_mae: 51033.7070
Epoch 95/100
250/250 [==============================] - 1s 3ms/step - loss: 51282.5898 - mae: 51282.5898 - val_loss: 50865.5352 - val_mae: 50865.5352
Epoch 96/100
250/250 [==============================] - 1s 3ms/step - loss: 51052.2383 - mae: 51052.2383 - val_loss: 50717.0430 - val_mae: 50717.0430
Epoch 97/100
250/250 [==============================] - 1s 3ms/step - loss: 50874.0469 - mae: 50874.0469 - val_loss: 50604.2031 - val_mae: 50604.2031
Epoch 98/100
250/250 [==============================] - 1s 3ms/step - loss: 50712.5078 - mae: 50712.5078 - val_loss: 50479.4961 - val_mae: 50479.4961
Epoch 99/100
250/250 [==============================] - 1s 3ms/step - loss: 50547.8438 - mae: 50547.8438 - val_loss: 50381.1914 - val_mae: 50381.1914
Epoch 100/100
250/250 [==============================] - 1s 3ms/step - loss: 50447.8984 - mae: 50447.8984 - val_loss: 50310.0312 - val_mae: 50310.0312

In [26]:
%load_ext tensorboard

In [29]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6015 (pid 31212), started 0:00:10 ago. (Use '!kill 31212' to kill it.)

In [30]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 984us/step - loss: 50167.8594 - mae: 50167.8594
Test MAE : 50167.859375

In [31]:
model.save('regression_model.h5')

e:\UDemy Final\ANN Classification\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(